# Generated by Django 3.0.2 on 2020-01-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='time',
            field=models.TimeField(auto_now_add=True, default='00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
