# Generated by Django 3.0.2 on 2020-01-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0002_auto_20200113_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='time',
        ),
    ]
