# Generated by Django 3.0.2 on 2020-01-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weights', '0003_remove_weight_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
